#! /usr/bin/env python
# [[file:../spdkit-python.note::3db7e946][3db7e946]]
from spdkit import *
import argparse
import sys

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='View molecule files in different applications')
    parser.add_argument('molfile', metavar='MOLFILE', type=str, help='path to molecule file')
    parser.add_argument('--app', metavar='APP', type=str, default='jmol', help='application to use for viewing (jmol, agui or pymol)')
    args = parser.parse_args()

    if args.app == 'jmol':
        p = view_in_jmol(io.read(args.molfile))
    elif args.app == 'pymol':
        p = view_traj_in_pymol(io.read(args.molfile))
    else:
        p = view_in_agui(io.read(args.molfile))
    p.wait()
# 3db7e946 ends here
